spring.application.name=auth-service
spring.data.mongodb.auto-index-creation=true
spring.mongodb.database=auth_db
spring.mongodb.port=27017
jwt.secret=your-base64-encoded-secret-here
# 15 minutes in seconds
jwt.expiration=900
# 7 days in seconds
jwt.refresh-expiration=604800
