spring:
  application:
    name: auth-service

  # MongoDB Configuration
  mongodb:
    uri: mongodb://${MONGO_ROOT_USER:admin}:${MONGO_ROOT_PASSWORD:deskflow_pass}@auth-mongodb:27017/auth-db?authSource=admin
  data:
    mongodb:
      auto-index-creation: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      acks: all

  # Jackson Configuration
  jackson:
    visibility:
      field: any

server:
  port: ${AUTH_PORT:8081}

jwt:
  # Pulls from .env; fallback to your current secret
  secret: ${JWT_SECRET:bPdGAxSjllAWFQj8KR5Nm0/2gz56Xc+tx+ZlqefIyW0=}
  expiration: ${JWT_EXPIRATION_SEC:900}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_SEC:604800}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data:
          mongodb: DEBUG
        kafka: DEBUG
