spring.application.name=auth-service
server.port=8081
spring.data.mongodb.auto-index-creation=true
spring.mongodb.database=auth_db
spring.mongodb.port=27017
jwt.secret=bPdGAxSjllAWFQj8KR5Nm0/2gz56Xc+tx+ZlqefIyW0=
# 15 minutes in seconds
jwt.expiration=900
# 7 days in seconds
jwt.refresh-expiration=604800
# Kafka Bootstrap Server (Host-accessible port)
spring.kafka.bootstrap-servers=localhost:9092
# Producer Config - serializers now handled in KafkaProducerConfig.java
spring.kafka.producer.acks=all
# Show exactly what is failing in the web layer
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
# This will show you every Kafka attempt
logging.level.org.springframework.kafka=DEBUG
# This ensures the Jackson JavaTimeModule is registered automatically
spring.jackson.visibility.field=any