services:
  # Database for Auth Service
  auth-mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=auth-db
    volumes:
      - auth-data:/data/db

  # Database for User Service
  user-mongodb:
    image: mongo:latest
    container_name: user-mongodb
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_DATABASE=user-db
    volumes:
      - user-data:/data/db

  # Database for Ticket Service
  ticket-mongodb:
    image: mongo:latest
    container_name: ticket-mongodb
    ports:
      - '27019:27017'
    environment:
      - MONGO_INITDB_DATABASE=ticket-db
    volumes:
      - ticket-data:/data/db

  # Database for Notification Service
  notification-mongodb:
    image: mongo:latest
    container_name: notification-mongodb
    ports:
      - '27020:27017'
    environment:
      - MONGO_INITDB_DATABASE=notification-db
    volumes:
      - notification-data:/data/db

  # Database for Analytics Service
  analytics-mongodb:
    image: mongo:latest
    container_name: analytics-mongodb
    ports:
      - '27021:27017' # Map host 27021 to container 27017
    environment:
      - MONGO_INITDB_DATABASE=analytics-db
    volumes:
      - analytics-data:/data/db

volumes:
  auth-data:
  user-data:
  ticket-data:
  notification-data:
  analytics-data:
