server:
  port: 8080

jwt:
  secret: bPdGAxSjllAWFQj8KR5Nm0/2gz56Xc+tx+ZlqefIyW0=

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # --- AUTH SERVICE ---
            - id: auth-role-management
              uri: http://localhost:8081
              predicates:
                - Path=/auth/role/**
              filters:
                - name: JwtAuthentication
                  args:
                    requiredRoles: [ "ADMIN" ]

            - id: auth-service-public
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**

            # --- USER SERVICE ---
            - id: user-service-internal-block
              uri: http://localhost:8082
              predicates:
                - Path=/users/internal/**
              filters:
                - SetStatus=403

            - id: user-service-me
              uri: http://localhost:8082
              predicates:
                - Path=/users/me
              filters:
                - name: JwtAuthentication
                  args:
                    requiredRoles: [ "SUBMITTER", "AGENT", "ADMIN" ]

            - id: user-service-lookup
              uri: http://localhost:8082
              predicates:
                - Path=/users/{id}, /users
              filters:
                - name: JwtAuthentication
                  args:
                    requiredRoles: [ "AGENT", "ADMIN" ]

            # --- TICKET SERVICE ---
            - id: ticket-service-my
              uri: http://localhost:8083
              predicates:
                - Path=/tickets/my
              filters:
                - name: JwtAuthentication
                  args:
                    requiredRoles: [ "SUBMITTER", "AGENT", "ADMIN" ]

            - id: ticket-service-staff
              uri: http://localhost:8083
              predicates:
                - Path=/tickets/**
              filters:
                - name: JwtAuthentication
                  args:
                    requiredRoles: [ "AGENT", "ADMIN" ]

            # --- NOTIFICATION SERVICE ---
            - id: notification-service
              uri: http://localhost:8084
              predicates:
                - Path=/notifications/**
              filters:
                - name: JwtAuthentication
                  args:
                    requiredRoles: [ "SUBMITTER", "AGENT", "ADMIN" ]

            # --- ANALYTICS SERVICE ---
            - id: analytics-service
              uri: http://localhost:8085
              predicates:
                - Path=/analytics/**
              filters:
                - name: JwtAuthentication
                  args:
                    requiredRoles: [ "ADMIN" ]

eureka:
  client:
    enabled: false