spring.application.name=user-service
# Database Connectivity
spring.mongodb.host=localhost
spring.mongodb.port=27018
spring.mongodb.database=user_db
spring.data.mongodb.auto-index-creation=true
# Kafka Bootstrap Server
spring.kafka.bootstrap-servers=localhost:9092
# Consumer Config
# IMPORTANT: Change this for each service (e.g., user-group, analytics-group)
spring.kafka.consumer.group-id=user-group
spring.kafka.consumer.auto-offset-reset=earliest
# Deserialization setup
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
# Security: Tell Jackson which packages are safe to deserialize
spring.kafka.consumer.properties.spring.json.trusted.packages=com.deskflow.*