spring.application.name=ticket-service
# Database Connectivity
spring.mongodb.host=localhost
spring.mongodb.port=27019
spring.mongodb.database=ticket_db
spring.data.mongodb.auto-index-creation=true
# Kafka Bootstrap Server (Host-accessible port)
spring.kafka.bootstrap-servers=localhost:9092
# Optional: Ensure the broker acknowledges the message
spring.kafka.producer.acks=all
# Show exactly what is failing in the web layer
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
# This will show you every Kafka attempt
logging.level.org.springframework.kafka=DEBUG
# This ensures the Jackson JavaTimeModule is registered automatically
spring.jackson.visibility.field=any