spring:
  application:
    name: ticket-service

  # MongoDB Configuration
  mongodb:
    uri: mongodb://${MONGO_ROOT_USER:admin}:${MONGO_ROOT_PASSWORD:deskflow_pass}@ticket-mongodb:27017/ticket-db?authSource=admin
  data:
    mongodb:
      auto-index-creation: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      acks: all

  # Jackson Configuration
  jackson:
    visibility:
      field: any

server:
  port: ${TICKET_PORT:8083}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data:
          mongodb: DEBUG
        kafka: DEBUG