spring.application.name=ticket-service
# Database Connectivity
spring.mongodb.host=localhost
spring.mongodb.port=27019
spring.mongodb.database=ticket_db
spring.data.mongodb.auto-index-creation=true
# Kafka Bootstrap Server (Host-accessible port)
spring.kafka.bootstrap-servers=localhost:9092
# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Optional: Ensure the broker acknowledges the message
spring.kafka.producer.acks=all